const PostsType = {
  GET_ALL_POSTS_SUCCESS: "GET_ALL_POSTS_SUCCESS",
  POSTS_LOADING: "POSTS_LOADING",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  GET_POST_DETAILS_SUCCESS: "GET_POST_DETAILS_SUCCESS",
  GET_POST_COMMENTS_SUCCESS: "GET_POST_COMMENTS_SUCCESS",
};
export default PostsType;
